In [1]:
import numpy as np
import numpy.linalg as la

def dveJed(x, xp):
    x1, x2, x3 = x
    x1p, x2p, x3p = xp

    A1 = [
        0, 0, 0,
        -x3p * x1, -x3p * x2, -x3p * x3,
         x2p * x1,  x2p * x2,  x2p * x3
    ]

    A2 = [
         x3p * x1,  x3p * x2,  x3p * x3,
         0, 0, 0,
        -x1p * x1, -x1p * x2, -x1p * x3
    ]

    return np.array(A1), np.array(A2)



def SVD(pts, pts_prime):
    jed = []
    for i in range(len(pts)):
        A1, A2 = dveJed(pts[i], pts_prime[i])
        jed.append(A1)
        jed.append(A2)

    jed = np.array(jed)

    U, S, Vh = la.svd(jed)
    P = Vh[-1].reshape(3, 3)

    return P / P[0, 0]


In [2]:
pts = [
    [1, 2, -3],
    [1, 0, -1],
    [1, 2, 0],
    [3, -2, 1]
]

pts_prime = [
    [-6, -7, 17],
    [-4, 1, 5],
    [9, 11, 26],
    [0, 23, 9]
]

H = SVD(pts, pts_prime)

print("Rezultat:")
print(H)

Rezultat:
[[1. 4. 5.]
 [7. 2. 6.]
 [8. 9. 3.]]
